[project]
name = "stock_picker"
version = "0.1.0"
description = "stock_picker using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.14"
dependencies = [
    "crewai>=1.15.10",
    "crewai-tools>=1.15.10",
    "pypushover>=0.2.7",
    "python-dotenv>=1.2.2",
    "requests>=2.34.2",
]

[project.scripts]
stock_picker = "stock_picker.main:run"
run_crew = "stock_picker.main:run"


[tool.crewai]
type = "crew"
